### YamlMime:ManagedReference
items:
- uid: UBP.Scripts.Data.Configs.DataConfig
  commentId: T:UBP.Scripts.Data.Configs.DataConfig
  id: DataConfig
  parent: UBP.Scripts.Data.Configs
  children:
  - UBP.Scripts.Data.Configs.DataConfig.ConfigsPath
  langs:
  - csharp
  - vb
  name: DataConfig
  nameWithType: DataConfig
  fullName: UBP.Scripts.Data.Configs.DataConfig
  type: Class
  source:
    remote:
      path: Assets/UBP/Scripts/Data/Configs/DataConfig.cs
      branch: main
      repo: https://github.com/y-games-hello/ultimate-base-project.git
    id: DataConfig
    path: ../Assets/UBP/Scripts/Data/Configs/DataConfig.cs
    startLine: 7
  namespace: UBP.Scripts.Data.Configs
  syntax:
    content: >-
      [CreateAssetMenu(fileName = "DataConfig", menuName = "Configs/DataConfig")]

      public class DataConfig : ScriptableObject
    content.vb: >-
      <CreateAssetMenu(fileName:="DataConfig", menuName:="Configs/DataConfig")>

      Public Class DataConfig Inherits ScriptableObject
  inheritance:
  - System.Object
  - UnityEngine.Object
  - UnityEngine.ScriptableObject
  attributes:
  - type: UnityEngine.CreateAssetMenuAttribute
    ctor: UnityEngine.CreateAssetMenuAttribute.#ctor
    arguments: []
    namedArguments:
    - name: fileName
      type: System.String
      value: DataConfig
    - name: menuName
      type: System.String
      value: Configs/DataConfig
- uid: UBP.Scripts.Data.Configs.DataConfig.ConfigsPath
  commentId: P:UBP.Scripts.Data.Configs.DataConfig.ConfigsPath
  id: ConfigsPath
  parent: UBP.Scripts.Data.Configs.DataConfig
  langs:
  - csharp
  - vb
  name: ConfigsPath
  nameWithType: DataConfig.ConfigsPath
  fullName: UBP.Scripts.Data.Configs.DataConfig.ConfigsPath
  type: Property
  source:
    remote:
      path: Assets/UBP/Scripts/Data/Configs/DataConfig.cs
      branch: main
      repo: https://github.com/y-games-hello/ultimate-base-project.git
    id: ConfigsPath
    path: ../Assets/UBP/Scripts/Data/Configs/DataConfig.cs
    startLine: 13
  namespace: UBP.Scripts.Data.Configs
  syntax:
    content: public string ConfigsPath { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ConfigsPath As String
  overload: UBP.Scripts.Data.Configs.DataConfig.ConfigsPath*
references:
- uid: UBP.Scripts.Data.Configs
  commentId: N:UBP.Scripts.Data.Configs
  href: UBP.html
  name: UBP.Scripts.Data.Configs
  nameWithType: UBP.Scripts.Data.Configs
  fullName: UBP.Scripts.Data.Configs
  spec.csharp:
  - uid: UBP
    name: UBP
    href: UBP.html
  - name: .
  - uid: UBP.Scripts
    name: Scripts
    href: UBP.Scripts.html
  - name: .
  - uid: UBP.Scripts.Data
    name: Data
    href: UBP.Scripts.Data.html
  - name: .
  - uid: UBP.Scripts.Data.Configs
    name: Configs
    href: UBP.Scripts.Data.Configs.html
  spec.vb:
  - uid: UBP
    name: UBP
    href: UBP.html
  - name: .
  - uid: UBP.Scripts
    name: Scripts
    href: UBP.Scripts.html
  - name: .
  - uid: UBP.Scripts.Data
    name: Data
    href: UBP.Scripts.Data.html
  - name: .
  - uid: UBP.Scripts.Data.Configs
    name: Configs
    href: UBP.Scripts.Data.Configs.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: UnityEngine.Object
  commentId: T:UnityEngine.Object
  parent: UnityEngine
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: UnityEngine.Object
- uid: UnityEngine.ScriptableObject
  commentId: T:UnityEngine.ScriptableObject
  parent: UnityEngine
  isExternal: true
  name: ScriptableObject
  nameWithType: ScriptableObject
  fullName: UnityEngine.ScriptableObject
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: UnityEngine
  commentId: N:UnityEngine
  isExternal: true
  name: UnityEngine
  nameWithType: UnityEngine
  fullName: UnityEngine
- uid: UBP.Scripts.Data.Configs.DataConfig.ConfigsPath*
  commentId: Overload:UBP.Scripts.Data.Configs.DataConfig.ConfigsPath
  href: UBP.Scripts.Data.Configs.DataConfig.html#UBP_Scripts_Data_Configs_DataConfig_ConfigsPath
  name: ConfigsPath
  nameWithType: DataConfig.ConfigsPath
  fullName: UBP.Scripts.Data.Configs.DataConfig.ConfigsPath
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
