### YamlMime:ManagedReference
items:
- uid: UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService
  commentId: T:UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService
  id: ApplicationEventsService
  parent: UBP.Scripts.UBPServices.ApplicationEvents
  children:
  - UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService.InitializeAsync
  - UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService.OnApplicationDestroy
  - UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService.OnApplicationFocus
  - UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService.OnApplicationPause
  - UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService.OnApplicationQuit
  langs:
  - csharp
  - vb
  name: ApplicationEventsService
  nameWithType: ApplicationEventsService
  fullName: UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService
  type: Class
  source:
    remote:
      path: Assets/UBP/Scripts/UBPServices/ApplicationEvents/ApplicationEventsService.cs
      branch: main
      repo: https://github.com/y-games-hello/ultimate-base-project.git
    id: ApplicationEventsService
    path: ../Assets/UBP/Scripts/UBPServices/ApplicationEvents/ApplicationEventsService.cs
    startLine: 11
  namespace: UBP.Scripts.UBPServices.ApplicationEvents
  summary: >-
    A centralized service that broadcasts application lifecycle events such as pause, focus, quit, and destroy.

    Allows non-MonoBehaviour systems to subscribe to Unity-level events.
  example: []
  syntax:
    content: 'public class ApplicationEventsService : IService'
    content.vb: Public Class ApplicationEventsService Implements IService
  inheritance:
  - System.Object
  implements:
  - UBP.Scripts.UBPServices.IService
- uid: UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService.OnApplicationPause
  commentId: F:UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService.OnApplicationPause
  id: OnApplicationPause
  parent: UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService
  langs:
  - csharp
  - vb
  name: OnApplicationPause
  nameWithType: ApplicationEventsService.OnApplicationPause
  fullName: UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService.OnApplicationPause
  type: Field
  source:
    remote:
      path: Assets/UBP/Scripts/UBPServices/ApplicationEvents/ApplicationEventsService.cs
      branch: main
      repo: https://github.com/y-games-hello/ultimate-base-project.git
    id: OnApplicationPause
    path: ../Assets/UBP/Scripts/UBPServices/ApplicationEvents/ApplicationEventsService.cs
    startLine: 13
  namespace: UBP.Scripts.UBPServices.ApplicationEvents
  syntax:
    content: public Action<bool> OnApplicationPause
    return:
      type: System.Action{System.Boolean}
    content.vb: Public OnApplicationPause As Action(Of Boolean)
- uid: UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService.OnApplicationFocus
  commentId: F:UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService.OnApplicationFocus
  id: OnApplicationFocus
  parent: UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService
  langs:
  - csharp
  - vb
  name: OnApplicationFocus
  nameWithType: ApplicationEventsService.OnApplicationFocus
  fullName: UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService.OnApplicationFocus
  type: Field
  source:
    remote:
      path: Assets/UBP/Scripts/UBPServices/ApplicationEvents/ApplicationEventsService.cs
      branch: main
      repo: https://github.com/y-games-hello/ultimate-base-project.git
    id: OnApplicationFocus
    path: ../Assets/UBP/Scripts/UBPServices/ApplicationEvents/ApplicationEventsService.cs
    startLine: 14
  namespace: UBP.Scripts.UBPServices.ApplicationEvents
  syntax:
    content: public Action<bool> OnApplicationFocus
    return:
      type: System.Action{System.Boolean}
    content.vb: Public OnApplicationFocus As Action(Of Boolean)
- uid: UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService.OnApplicationQuit
  commentId: F:UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService.OnApplicationQuit
  id: OnApplicationQuit
  parent: UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService
  langs:
  - csharp
  - vb
  name: OnApplicationQuit
  nameWithType: ApplicationEventsService.OnApplicationQuit
  fullName: UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService.OnApplicationQuit
  type: Field
  source:
    remote:
      path: Assets/UBP/Scripts/UBPServices/ApplicationEvents/ApplicationEventsService.cs
      branch: main
      repo: https://github.com/y-games-hello/ultimate-base-project.git
    id: OnApplicationQuit
    path: ../Assets/UBP/Scripts/UBPServices/ApplicationEvents/ApplicationEventsService.cs
    startLine: 15
  namespace: UBP.Scripts.UBPServices.ApplicationEvents
  syntax:
    content: public Action OnApplicationQuit
    return:
      type: System.Action
    content.vb: Public OnApplicationQuit As Action
- uid: UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService.OnApplicationDestroy
  commentId: F:UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService.OnApplicationDestroy
  id: OnApplicationDestroy
  parent: UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService
  langs:
  - csharp
  - vb
  name: OnApplicationDestroy
  nameWithType: ApplicationEventsService.OnApplicationDestroy
  fullName: UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService.OnApplicationDestroy
  type: Field
  source:
    remote:
      path: Assets/UBP/Scripts/UBPServices/ApplicationEvents/ApplicationEventsService.cs
      branch: main
      repo: https://github.com/y-games-hello/ultimate-base-project.git
    id: OnApplicationDestroy
    path: ../Assets/UBP/Scripts/UBPServices/ApplicationEvents/ApplicationEventsService.cs
    startLine: 20
  namespace: UBP.Scripts.UBPServices.ApplicationEvents
  summary: Called when the application is destroyed.
  example: []
  syntax:
    content: public Action OnApplicationDestroy
    return:
      type: System.Action
    content.vb: Public OnApplicationDestroy As Action
- uid: UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService.InitializeAsync
  commentId: M:UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService.InitializeAsync
  id: InitializeAsync
  parent: UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService
  langs:
  - csharp
  - vb
  name: InitializeAsync()
  nameWithType: ApplicationEventsService.InitializeAsync()
  fullName: UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService.InitializeAsync()
  type: Method
  source:
    remote:
      path: Assets/UBP/Scripts/UBPServices/ApplicationEvents/ApplicationEventsService.cs
      branch: main
      repo: https://github.com/y-games-hello/ultimate-base-project.git
    id: InitializeAsync
    path: ../Assets/UBP/Scripts/UBPServices/ApplicationEvents/ApplicationEventsService.cs
    startLine: 25
  namespace: UBP.Scripts.UBPServices.ApplicationEvents
  summary: Initializes the application event dispatcher and ensures it persists across scenes.
  example: []
  syntax:
    content: public Task InitializeAsync()
    return:
      type: System.Threading.Tasks.Task
    content.vb: Public Function InitializeAsync() As Task
  overload: UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService.InitializeAsync*
  implements:
  - UBP.Scripts.UBPServices.IService.InitializeAsync
references:
- uid: UBP.Scripts.UBPServices.ApplicationEvents
  commentId: N:UBP.Scripts.UBPServices.ApplicationEvents
  href: UBP.html
  name: UBP.Scripts.UBPServices.ApplicationEvents
  nameWithType: UBP.Scripts.UBPServices.ApplicationEvents
  fullName: UBP.Scripts.UBPServices.ApplicationEvents
  spec.csharp:
  - uid: UBP
    name: UBP
    href: UBP.html
  - name: .
  - uid: UBP.Scripts
    name: Scripts
    href: UBP.Scripts.html
  - name: .
  - uid: UBP.Scripts.UBPServices
    name: UBPServices
    href: UBP.Scripts.UBPServices.html
  - name: .
  - uid: UBP.Scripts.UBPServices.ApplicationEvents
    name: ApplicationEvents
    href: UBP.Scripts.UBPServices.ApplicationEvents.html
  spec.vb:
  - uid: UBP
    name: UBP
    href: UBP.html
  - name: .
  - uid: UBP.Scripts
    name: Scripts
    href: UBP.Scripts.html
  - name: .
  - uid: UBP.Scripts.UBPServices
    name: UBPServices
    href: UBP.Scripts.UBPServices.html
  - name: .
  - uid: UBP.Scripts.UBPServices.ApplicationEvents
    name: ApplicationEvents
    href: UBP.Scripts.UBPServices.ApplicationEvents.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: UBP.Scripts.UBPServices.IService
  commentId: T:UBP.Scripts.UBPServices.IService
  parent: UBP.Scripts.UBPServices
  href: UBP.Scripts.UBPServices.IService.html
  name: IService
  nameWithType: IService
  fullName: UBP.Scripts.UBPServices.IService
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: UBP.Scripts.UBPServices
  commentId: N:UBP.Scripts.UBPServices
  href: UBP.html
  name: UBP.Scripts.UBPServices
  nameWithType: UBP.Scripts.UBPServices
  fullName: UBP.Scripts.UBPServices
  spec.csharp:
  - uid: UBP
    name: UBP
    href: UBP.html
  - name: .
  - uid: UBP.Scripts
    name: Scripts
    href: UBP.Scripts.html
  - name: .
  - uid: UBP.Scripts.UBPServices
    name: UBPServices
    href: UBP.Scripts.UBPServices.html
  spec.vb:
  - uid: UBP
    name: UBP
    href: UBP.html
  - name: .
  - uid: UBP.Scripts
    name: Scripts
    href: UBP.Scripts.html
  - name: .
  - uid: UBP.Scripts.UBPServices
    name: UBPServices
    href: UBP.Scripts.UBPServices.html
- uid: System.Action{System.Boolean}
  commentId: T:System.Action{System.Boolean}
  parent: System
  definition: System.Action`1
  name: Action<bool>
  nameWithType: Action<bool>
  fullName: System.Action<bool>
  nameWithType.vb: Action(Of Boolean)
  fullName.vb: System.Action(Of Boolean)
  name.vb: Action(Of Boolean)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    isExternal: true
  - name: <
  - uid: System.Boolean
    name: bool
    isExternal: true
  - name: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - uid: System.Boolean
    name: Boolean
    isExternal: true
  - name: )
- uid: System.Action`1
  commentId: T:System.Action`1
  isExternal: true
  name: Action<T>
  nameWithType: Action<T>
  fullName: System.Action<T>
  nameWithType.vb: Action(Of T)
  fullName.vb: System.Action(Of T)
  name.vb: Action(Of T)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    isExternal: true
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    isExternal: true
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: System.Action
  commentId: T:System.Action
  parent: System
  isExternal: true
  name: Action
  nameWithType: Action
  fullName: System.Action
- uid: UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService.InitializeAsync*
  commentId: Overload:UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService.InitializeAsync
  href: UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService.html#UBP_Scripts_UBPServices_ApplicationEvents_ApplicationEventsService_InitializeAsync
  name: InitializeAsync
  nameWithType: ApplicationEventsService.InitializeAsync
  fullName: UBP.Scripts.UBPServices.ApplicationEvents.ApplicationEventsService.InitializeAsync
- uid: UBP.Scripts.UBPServices.IService.InitializeAsync
  commentId: M:UBP.Scripts.UBPServices.IService.InitializeAsync
  parent: UBP.Scripts.UBPServices.IService
  href: UBP.Scripts.UBPServices.IService.html#UBP_Scripts_UBPServices_IService_InitializeAsync
  name: InitializeAsync()
  nameWithType: IService.InitializeAsync()
  fullName: UBP.Scripts.UBPServices.IService.InitializeAsync()
  spec.csharp:
  - uid: UBP.Scripts.UBPServices.IService.InitializeAsync
    name: InitializeAsync
    href: UBP.Scripts.UBPServices.IService.html#UBP_Scripts_UBPServices_IService_InitializeAsync
  - name: (
  - name: )
  spec.vb:
  - uid: UBP.Scripts.UBPServices.IService.InitializeAsync
    name: InitializeAsync
    href: UBP.Scripts.UBPServices.IService.html#UBP_Scripts_UBPServices_IService_InitializeAsync
  - name: (
  - name: )
- uid: System.Threading.Tasks.Task
  commentId: T:System.Threading.Tasks.Task
  parent: System.Threading.Tasks
  isExternal: true
  name: Task
  nameWithType: Task
  fullName: System.Threading.Tasks.Task
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
  spec.vb:
  - uid: System
    name: System
    isExternal: true
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
